Repository swift-in-gangnam/soil, pull requests merged in 2021-11, with the labels that each got.

#2 [Fix] TabBar / NaviBar issues on iOS15
  .github/PULL_REQUEST_TEMPLATE.md
  Soil.xcodeproj/project.pbxproj
  Soil/Controller/FeedController.swift
  Soil/Controller/TabBarController.swift
  Soil/Controller/UploadPostController.swift
  Soil/Controller/YouController.swift
Labels: Type: bug, Priority: medium, Type: refactor

#4 docs: add CONTRIBUTING.md
  CONTRIBUTING.md
  Soil.xcodeproj/project.pbxproj
Labels: Type: docs, Priority: ASAP

#6 feat: add PaingVC with Parchment
  Soil.xcodeproj/project.pbxproj
  Soil/Controller/Authentication/RegistrationController.swift
  Soil/Controller/DayController.swift
  Soil/Controller/MonthController.swift
  Soil/Controller/ProfileController.swift
  Soil/Controller/YearController.swift
  Soil/Controller/YouController.swift
Labels: Priority: medium, Type: feat

#10 feat: implement ProfileController
  .swiftlint.yml
  Soil.xcodeproj/project.pbxproj
  Soil/Controller/Profile/EditProfileController.swift
  Soil/Controller/Profile/ProfileController.swift
  Soil/Controller/Profile/UserStatController.swift
  Soil/Controller/ProfileController.swift
  Soil/Controller/YouController.swift
  Soil/Model/User.swift
  Soil/ViewModel/ProfileViewModel.swift
Labels: Priority: medium, Type: feat

#12 feat: implement UploadPostController UI (#7)
  .swiftlint.yml
  Soil.xcodeproj/project.pbxproj
  Soil.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Soil/Controller/UploadPostController.swift
  Soil/Supporting/Info.plist
  Soil/Supporting/SceneDelegate.swift
  Soil/View/HorizontalSeperator.swift
  Soil/View/UploadPostInputAccessoryView.swift
Labels: Type: feat, Priority: ASAP

#15 style: correct some properties' name & simplify code related to UploadController
  Soil/Controller/UploadPostController.swift
  Soil/View/UploadPostInputAccessoryView.swift
Labels: Priority: medium, Type: style

#16 feat: implement SignUp UI
  Soil.xcodeproj/project.pbxproj
  Soil/Controller/Auth/EmailConfirmController.swift
  Soil/Controller/Auth/EmailInputViewController.swift
  Soil/Controller/Auth/LoginHomeController.swift
  Soil/Controller/Auth/NameInputController.swift
  Soil/Controller/Auth/NickNameInputController.swift
  Soil/Controller/Auth/PasswordInputController.swift
  Soil/Controller/Auth/ProfileInputController.swift
  Soil/Controller/Auth/SignInController.swift
  Soil/Controller/Auth/SignUpCompleteController.swift
  Soil/Controller/Auth/SignUpCompletedController.swift
  Soil/Controller/TabBarController.swift
  Soil/Controller/YouController.swift
  Soil/Supporting/Assets.xcassets/Button Images/ProfileButton.imageset/Contents.json
  Soil/Supporting/Assets.xcassets/Button Images/ProfileButton.imageset/ProfileButton@2x.png
  Soil/Supporting/Assets.xcassets/Button Images/ProfileButton.imageset/ProfileButton@3x.png
  Soil/Supporting/Assets.xcassets/Button Images/ProfileButton.imageset/Profile_Img.png
  Soil/Supporting/Lottie/email-sent.json
  Soil/Supporting/Lottie/task-completed.json
  Soil/View/Auth/Auth.storyboard
  Soil/View/Auth/CustomPasswordTextField.swift
  Soil/View/Auth/CustomTextField.swift
Labels: Priority: medium, Type: feat

#24 feat: implement SignIn using Firebase (#17)
  Soil.xcodeproj/project.pbxproj
  Soil/Controller/Auth/SignInController.swift
  Soil/Controller/TabBarController.swift
  Soil/Controller/YouController.swift
  Soil/View/Auth/Auth.storyboard
  Soil/View/Auth/CustomTextField.swift
Labels: Priority: medium, Type: feat

#26 fix: fix inputAccessoryView's close button to be hidden when keyboard disappear (#14)
  Soil.xcodeproj/project.pbxproj
  Soil/Controller/UploadPostController.swift
  Soil/View/UploadPostInputAccessoryView.swift
Labels: Type: bug, Priority: medium

#27 feat: implement EditProfileController
  Soil.xcodeproj/project.pbxproj
  Soil/API/StorageService.swift
  Soil/API/UserService.swift
  Soil/Controller/Profile/EditProfileController.swift
  Soil/Controller/Profile/ProfileController.swift
  Soil/Controller/TabBarController.swift
  Soil/Utils/Constants.swift
  Soil/Utils/Extensions/UITextFieldExtension.swift
  Soil/ViewModel/ProfileViewModel.swift
Labels: Priority: medium, Type: feat
